services:
  target-almalinux:
    container_name: target-almalinux
    hostname: target-almalinux
    image: my-almalinux
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile_almalinux
      args:
        HTTP_PROXY: "${HTTP_PROXY}"
        HTTPS_PROXY: "${HTTPS_PROXY}"
        NO_PROXY: "${NO_PROXY}"
        LINUX_ROOT_PASSWORD: ${LINUX_ROOT_PASSWORD:-P@ssw0rd}
        LINUX_USER_PASSWORD: ${LINUX_USER_PASSWORD:-password}
      secrets:
        - host_certificate_file
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - http_proxy=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - https_proxy=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${NO_PROXY}
    networks:
      - ansible-net
    # ports:
    #   - "2222:22" # リモート機器へのSSH接続ポート
    expose:
      - 22
    volumes:
      - ${HOST_CERTIFICATE_FILE:-/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem}:${HOST_CERTIFICATE_FILE:-/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem}:ro
